apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/patch-operator
- ../../base/operators.coreos.com/operatorgroups/patch-operator
- ../../base/operators.coreos.com/subscriptions/patch-operator
