apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: local-ops-rbac

namePrefix: local-

resources:
  - ../ops-rbac

patches:
  - target:
      labelSelector: nerc.mghpcc.org/aggregate-to-ops=true
    patch: |
      - op: remove
        path: /metadata/labels/nerc.mghpcc.org~1aggregate-to-ops
      - op: add
        path: /metadata/labels/nerc.mghpcc.org~1aggregate-to-local-ops
        value: "true"
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: ops
      aggregationRule:
        clusterRoleSelectors:
        - matchLabels:
            nerc.mghpcc.org/aggregate-to-local-ops: "true"
        - matchLabels:
            rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
        - matchLabels:
            rbac.authorization.k8s.io/aggregate-to-view: "true"
