# Source: csi-wekafsplugin/templates/controllerserver-rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-wekafsplugin-controller
  labels:
    app: csi-wekafsplugin-controller
    component: csi-wekafsplugin-controller
    release: csi-wekafsplugin
  namespace: csi-wekafsplugin
subjects:
  - kind: ServiceAccount
    name: csi-wekafsplugin-controller
    namespace: csi-wekafsplugin
roleRef:
  kind: Role
  name: csi-wekafsplugin-controller
  apiGroup: rbac.authorization.k8s.io
