apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage

commonLabels:
  nerc.mghpcc.org/feature: odf

resources:
  - ../../../../bundles/odf-external

patches:
  - path: subscriptions/subscription-patch.yaml
