apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client-secret
  namespace: grafana
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: oauth-client-secret
  data:
  - secretKey: GRAFANA_SECRET
    remoteRef:
      key: nerc/nerc-ocp-infra/dex/dex-clients
      property: GRAFANA_SECRET
