apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: metrics-bucket-class
  namespace: openshift-storage
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - metrics-backing-store
