apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.10
  clusterID: c17c3ede-423f-4db6-8313-3d0ef3d543c7
  desiredUpdate:
    image: >-
      quay.io/openshift-release-dev/ocp-release@sha256:ddcb70ce04a01ce487c0f4ad769e9e36a10c8c832a34307c1b1eb8e03a5b7ddb
    version: 4.10.15
