apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/metallb
- ../../bundles/patch-operator
- ../../bundles/xdmod-reader
- feature/odf
- feature/external-ingress
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- apiserver/cluster.yaml
- secretstores
- machineconfigs/configure-bond0
- machineconfigs/set-rpfilter-loose
- machineconfigs/public-ingress
- nodenetworkconfigurationpolicies
- metallb
- clusterversion.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-monitoring-config
    namespace: openshift-monitoring
    files:
      - config.yaml=configmaps/cluster-monitoring-config.yaml

patches:
- path: ingresscontrollers/default_patch.yaml
- path: oauths/cluster_patch.yaml

- target:
    group: "metallb.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "operator.external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "nmstate.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "redhatcop.redhat.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"
