apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-ha
  labels:
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/name: postgresql-ha
automountServiceAccountToken: false
