apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-clients
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: dex-clients
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/dex/dex-clients     # Patch $ENV/$CLUSTER in overlay
