apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: nerc-certificate-clusterissuer

resources:
- ../../base/external-secrets.io/externalsecrets/clusterissuer-dns01
- ../../cert-manager.io/clusterissuers/letsencrypt-production-dns01
- ../../cert-manager.io/clusterissuers/letsencrypt-staging-dns01
