apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: nfs
resources:
  - core/namespaces
  - core/serviceaccounts
  - rbac.authorization.k8s.io/rolebindings
  - core/persistentvolumeclaims
  - core/deployments
  - core/services
