apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: ExternalSecret
    name: openshift-logging-lokistack-gateway-bearer-token
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/nerc-ocp-obs/lokistack-gateway-bearer-token
