apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - path: externalsecrets/solr-externalsecret.yaml
  - path: externalsecrets/postgresql-ha-pgpool-externalsecret.yaml
  - path: externalsecrets/postgresql-ha-externalsecret.yaml
