apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - externalsecrets/
  - grafanas/grafana.yaml
  - grafanadatasources/grafanadatasource.yaml
  - patches/grafana-oauth.yaml
  - patches/grafanadatasource-observability-metrics.yaml

patches:
  - path: patches/grafana-route.yaml

secretGenerator:
  - name: grafana-serviceaccount-token
    type: kubernetes.io/service-account-token
    options:
      disableNameSuffixHash: true
      annotations:
        kubernetes.io/service-account.name: grafana-serviceaccount
