# Source: csi-wekafsplugin/templates/nodeserver-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-wekafsplugin-node
  labels:
    app: csi-wekafsplugin-node
    component: csi-wekafsplugin-node
    release: csi-wekafsplugin
subjects:
  - kind: ServiceAccount
    name: csi-wekafsplugin-node
    namespace: csi-wekafsplugin
roleRef:
  kind: ClusterRole
  name: csi-wekafsplugin-node
  apiGroup: rbac.authorization.k8s.io
