apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snmp-exporter
resources:
  - persistentvolumeclaim.yaml
  - deployment-prometheus-snmp-exporter.yaml
  - role-prometheus-snmp-exporter.yaml
  - rolebinding-prometheus-snmp-exporter.yaml
  - service-prometheus-snmp-exporter.yaml
  - serviceaccount-prometheus-snmp-exporter.yaml
  - servicemonitor-prometheus-snmp-exporter-vlan-935-moc-swmon.yaml
  - configmap-observability-metrics-custom-allowlist.yaml
