apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: eth-nese
spec:
  nodeSelector:
    gpu: "false"
  desiredState:
    interfaces:
    - name: mlx1
      type: ethernet
      state: up
      ipv4:
        dhcp: true
        enabled: true
        auto-routes: true
      mtu: 9000
