apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-router-external-apps-service
spec:
  serviceAccountRef:
    name: patcher
  patches:
    patch-router-external-apps-service:
      targetObjectRef:
        apiVersion: v1
        kind: Service
        name: router-external-apps
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            metallb.universe.tf/address-pool: public
          name: router-external-apps
          namespace: openshift-ingress
        spec:
          loadBalancerIP: 199.94.61.6
