apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-cluster-management-observability-multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: multiclusterhub-operator-pull-secret
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/open-cluster-management-observability-multiclusterhub-operator-pull-secret
