apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  namespace: openshift-config
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
      - names:
        - api.nerc-ocp-infra.rc.fas.harvard.edu
        servingCertificate:
          name: default-api-certificate
