apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: autopilot
  name: autopilot
  namespace: autopilot
spec:
  selector:
    matchLabels:
      app: autopilot
  template:
    metadata:
      annotations:
        null
      labels:
        app: autopilot
    spec:
      nodeSelector:
        nvidia.com/gpu.present: 'true'
      serviceAccountName: autopilot
      initContainers:
        - args:
          - |
            until [ -f /usr/bin/nvidia-smi ]; do echo waiting for nvidia device plug-in to be setup; sleep 5 && exit -1; done
          command:
          - sh
          - -c
          image: quay.io/autopilot/autopilot:v1.9.0
          imagePullPolicy: Always
          name: device-plugin-validation
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
      containers:
        - image: quay.io/autopilot/autopilot:v1.9.0
          command:
          - sh
          - -c
          - |
            iperf3 -s -p 6310 -D
            /usr/local/bin/autopilot --port 3333 --loglevel=2 --bw 4 --w 1 --invasive-check-timer 4
          imagePullPolicy: Always
          name: autopilot
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          env:
            - name: PERIODIC_CHECKS
              value: pciebw,remapped,dcgm,ping,gpupower
            - name: PVC_TEST_STORAGE_CLASS
              value:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3333
              name: healthcheck
            - containerPort: 8081
              name: http
            - containerPort: 8080
              name: readinessprobe
          readinessProbe:
            httpGet:
              path: /readinessprobe
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 120
            timeoutSeconds: 10
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 120
            timeoutSeconds: 15
            exec:
              command:
                - nvidia-smi
          resources:
            limits:
              nvidia.com/gpu: 0
            requests:
              nvidia.com/gpu: 0
          volumeMounts: []
      volumes: []
