apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: grafana-oauth
  namespace: grafana
spec:
  serviceAccountRef:
    name: patcher
  patches:
    logging-grafana-patch:
      targetObjectRef:
        apiVersion: integreatly.org/v1alpha1
        kind: Grafana
        name: grafana
        namespace: grafana
      patchTemplate: |
        spec:
          config:
            server:
              root_url: https://grafana.apps.nerc-ocp-infra.rc.fas.harvard.edu
            auth.generic_oauth:
              client_id: grafana
              client_secret: {{ (index . 1).data.GRAFANA_SECRET | b64dec }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        name: oauth-client-secret
        namespace: grafana
