apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: external-secrets
resources:
- ../../base/core/namespaces/external-secrets-operator
- ../../base/core/serviceaccounts/eso-vault-auth
- ../../base/operator.external-secrets.io/operatorconfigs/cluster
- ../../base/operators.coreos.com/subscriptions/external-secrets-operator
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/eso-tokenreview
- ../../base/operators.coreos.com/operatorgroups/external-secrets
- ../../base/core/secrets/eso-vault-auth-token/
