apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nerc-cluster-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "nerc"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes/
          role: secret-reader
          serviceAccountRef:
            name: "vault-secret-reader"
            namespace: "external-secrets-operator"
