apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-cluster-management-observability-thanos-object-storage
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: thanos-object-storage
    template:
      type: Opaque
      engineVersion: v2
      data:
        thanos.yaml: |
          type: s3
          config:
            bucket: "{{ .bucket }}"
            endpoint: "{{ .endpoint }}"
            insecure: false
            access_key: "{{ .access_key }}"
            secret_key: "{{ .secret_key }}"
            http_config:
              tls_config:
                ca_file: "/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
  data:
  - secretKey: bucket
    remoteRef:
      key: $ENV/$CLUSTER/open-cluster-management-observability-thanos-object-storage
      property: bucket
  - secretKey: endpoint
    remoteRef:
      key: $ENV/$CLUSTER/open-cluster-management-observability-thanos-object-storage
      property: endpoint
  - secretKey: access_key
    remoteRef:
      key: $ENV/$CLUSTER/open-cluster-management-observability-thanos-object-storage
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: $ENV/$CLUSTER/open-cluster-management-observability-thanos-object-storage
      property: secret_key
