apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  generateBucketName: observability
  storageClassName: openshift-storage.noobaa.io
