---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-application-view-binding-nerc-logs-metrics
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-application-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: nerc-logs-metrics

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-infrastructure-view-binding-nerc-logs-metrics
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-infrastructure-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: nerc-logs-metrics

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-audit-view-binding-nerc-logs-metrics
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-audit-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: nerc-logs-metrics
