apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: observability-metrics
  namespace: grafana
spec:
  name: observability-metrics
  datasources:
    - name: observability-metrics
      access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsAuthWithCACert: true
      secureJsonData:
        httpHeaderValue1: |-
          Bearer REPLACE_IN_OVERLAY
        tlsCACert: >-
          REPLACE_IN_OVERLAY
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/'
