apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: observability-metrics
  namespace: grafana
spec:
  name: observability-metrics
  datasources:
    - name: observability-metrics
      access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsAuthWithCACert: true
      secureJsonData:
        httpHeaderValue1: "Bearer ${token}"
        tlsCACert: "${service-ca.crt}"
      type: prometheus
      url: 'http://observability-thanos-query.open-cluster-management-observability.svc.cluster.local:9090/'
