# Source: csi-wekafsplugin/templates/nodeserver-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-wekafsplugin-node
  namespace: csi-wekafsplugin
  labels:
    app: csi-wekafsplugin-node
    component: csi-wekafsplugin-node
    release: csi-wekafsplugin
