---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patch-operator
  namespace: patch-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      requests:
        memory: "512Mi"
        cpu: "1000m"
      limits:
        memory: "1024Mi"
        cpu: "1500m"
