apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/openshift-logging
- ../../base/operators.coreos.com/operatorgroups/openshift-logging
- ../../base/operators.coreos.com/subscriptions/cluster-logging
- ../../base/operators.coreos.com/subscriptions/elasticsearch-operator/
