apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: 771ea98004d436c6e529
        clientSecret:
          name: github-client-secret
        teams:
          - ocp-on-nerc/nerc-ops
          - ocp-on-nerc/nerc-logs-metrics
