apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: nerc-ocp-test-2
  namespace: nerc-ocp-test-2
spec:
  clusterName: nerc-ocp-test-2
  clusterNamespace: nerc-ocp-test-2
  clusterLabels:
    name: nerc-ocp-test-2
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
