apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
namespace: openshift-operators-redhat
metadata:
  name: lokistack-config-custom
  namespace: openshift-operators-redhat
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: lokistack-config-custom
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        namespace: open-cluster-management-observability
      data:
        config.yaml: |
          ---
          auth_enabled: true
          chunk_store_config:
            chunk_cache_config:
              enable_fifocache: true
              fifocache:
                max_size_bytes: 500MB
          common:
            storage:
              s3:
                s3: "{{ .endpoint }}"
                bucketnames: "{{ .bucketnames }}"
                access_key_id: "{{ .access_key_id }}"
                secret_access_key: "{{ .access_key_secret }}"
                s3forcepathstyle: true
                http_config:
                  ca_file: "/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          compactor:
            compaction_interval: 2h
            working_directory: /tmp/loki/compactor
          frontend:
            tail_proxy_url: http://lokistack-querier-http.openshift-operators-redhat.svc.cluster.local:3100
            compress_responses: true
            max_outstanding_per_tenant: 256
            log_queries_longer_than: 5s
          frontend_worker:
            frontend_address: lokistack-query-frontend-grpc.openshift-operators-redhat.svc.cluster.local:9095
            grpc_client_config:
              max_send_msg_size: 104857600
            match_max_concurrent: true
          ingester:
            chunk_block_size: 262144
            chunk_encoding: snappy
            chunk_idle_period: 1h
            chunk_retain_period: 5m
            chunk_target_size: 2097152
            flush_op_timeout: 10m
            max_chunk_age: 1000h
            lifecycler:
              final_sleep: 0s
              heartbeat_period: 5s
              join_after: 30s
              num_tokens: 512
              ring:
                replication_factor: 1
                heartbeat_timeout: 1m
            max_transfer_retries: 0
            wal:
              enabled: true
              dir: /tmp/wal
              replay_memory_ceiling: 536870912
          ingester_client:
            grpc_client_config:
              max_recv_msg_size: 67108864
            remote_timeout: 1s
          # NOTE: Keep the order of keys as in Loki docs
          # to enable easy diffs when vendoring newer
          # Loki releases.
          # (See https://grafana.com/docs/loki/latest/configuration/#limits_config)
          #
          # Values for not exposed fields are taken from the grafana/loki production
          # configuration manifests.
          # (See https://github.com/grafana/loki/blob/main/production/ksonnet/loki/config.libsonnet)
          limits_config:
            ingestion_rate_strategy: global
            ingestion_rate_mb: 10000
            ingestion_burst_size_mb: 10000
            max_label_name_length: 1024
            max_label_value_length: 2048
            max_label_names_per_series: 30
            reject_old_samples: false
            reject_old_samples_max_age: 100d
            creation_grace_period: 10m
            enforce_metric_name: false
            # Keep max_streams_per_user always to 0 to default
            # using max_global_streams_per_user always.
            # (See https://github.com/grafana/loki/blob/main/pkg/ingester/limiter.go#L73)
            max_streams_per_user: 0
            max_line_size: 256000
            max_entries_limit_per_query: 5000
            max_global_streams_per_user: 0
            max_chunks_per_query: 2000000
            max_query_length: 721h
            max_query_parallelism: 32
            max_query_series: 500
            cardinality_limit: 100000
            max_streams_matchers_per_query: 1000
            max_cache_freshness_per_query: 10m
            per_stream_rate_limit: 1000MB
            per_stream_rate_limit_burst: 1000MB
            split_queries_by_interval: 30m
          memberlist:
            abort_if_cluster_join_fails: true
            bind_port: 7946
            join_members:
              - lokistack-gossip-ring.openshift-operators-redhat.svc.cluster.local:7946
            max_join_backoff: 1m
            max_join_retries: 10
            min_join_backoff: 1s
          querier:
            engine:
              max_look_back_period: 30s
              timeout: 3m
            extra_query_delay: 0s
            query_ingesters_within: 3h
            query_timeout: 1m
            tail_max_duration: 1h
            max_concurrent: 1
            multi_tenant_queries_enabled: true
          query_range:
            align_queries_with_step: true
            cache_results: true
            max_retries: 5
            results_cache:
              cache:
                enable_fifocache: true
                fifocache:
                  max_size_bytes: 500MB
            parallelise_shardable_queries: true
          schema_config:
            configs:
              - from: "2020-10-11"
                index:
                  period: 24h
                  prefix: index_
                object_store: s3
                schema: v11
                store: boltdb-shipper
          
          server:
            graceful_shutdown_timeout: 5s
            grpc_server_min_time_between_pings: '10s'
            grpc_server_ping_without_stream_allowed: true
            grpc_server_max_concurrent_streams: 1000
            grpc_server_max_recv_msg_size: 104857600
            grpc_server_max_send_msg_size: 104857600
            http_listen_port: 3100
            http_server_idle_timeout: 120s
            http_server_write_timeout: 1m
            log_level: debug
          storage_config:
            boltdb_shipper:
              active_index_directory: /tmp/loki/index
              cache_location: /tmp/loki/index_cache
              cache_ttl: 24h
              resync_interval: 5m
              shared_store: s3
              index_gateway_client:
                server_address: dns:///lokistack-index-gateway-grpc.openshift-operators-redhat.svc.cluster.local:9095
          tracing:
            enabled: false
          analytics:
            reporting_enabled: false
        runtime-config.yaml: |
          overrides: 
  data:
  - secretKey: endpoint
    remoteRef:
      key: $ENV/$CLUSTER/loki-thanos-object-storage
      property: endpoint
  - secretKey: bucketnames
    remoteRef:
      key: $ENV/$CLUSTER/loki-thanos-object-storage
      property: bucketnames
  - secretKey: access_key_id
    remoteRef:
      key: $ENV/$CLUSTER/loki-thanos-object-storage
      property: access_key_id
  - secretKey: access_key_secret
    remoteRef:
      key: $ENV/$CLUSTER/loki-thanos-object-storage
      property: access_key_secret
