apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operatorgroups/
  - subscriptions/
  - configmaps/
  - routes/
  - serviceaccounts/
  - clusterrolebindings/grafana-node-labeler-patcher/
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana
  app.kubernetes.io/part-of: observability
