apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: group-sync-operator
spec:
    channel: alpha
    installPlanApproval: Manual
    name: group-sync-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
