apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/xdmod/
- ../../base/core/serviceaccounts/xdmod-reader/
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/xdmod-reader-xdmod-permissions/
- ../../base/rbac.authorization.k8s.io/clusterroles/xdmod-permissions/
