apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config

resources:
- console-external-certificate.cert
- downloads-external-certificate.cert
- oauth-external-certificate.cert
- nerc-external-apps-issuer.yaml
- nerc-route53-creds.yaml
