apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: remoteloki
      type: loki
      url: https://logging-loki-openshift-logging.apps.nerc-ocp-obs.rc.fas.harvard.edu/api/logs/v1/application
  pipelines:
  - name: all-to-loki
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - remoteloki
