# Source: csi-wekafsplugin/templates/controllerserver-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-wekafsplugin-controller
  labels:
    app: csi-wekafsplugin-controller
    component: csi-wekafsplugin-controller
    release: csi-wekafsplugin
subjects:
  - kind: ServiceAccount
    name: csi-wekafsplugin-controller
    namespace: csi-wekafsplugin
roleRef:
  kind: ClusterRole
  name: csi-wekafsplugin-controller
  apiGroup: rbac.authorization.k8s.io
