apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/core/namespaces/openshift-logging
  - ../../base/operators.coreos.com/subscriptions/elasticsearch-operator
  - ../../base/loki.grafana.com/elasticsearches/elasticsearch
  - ../../base/operators.coreos.com/operatorgroups/openshift-logging
  - ../../base/operators.coreos.com/subscriptions/cluster-logging
  - ../../base/logging.openshift.io/clusterloggings/instance
  - ../../base/logging.openshift.io/clusterlogforwarders/instance
#  - ../../base/policy.open-cluster-management.io/policies/policy-enableclusterlogforwarder
#  - ../../base/policy.open-cluster-management.io/placementbindings/binding-policy-enableclusterlogforwarder
#  - ../../base/policy.open-cluster-management.io/placementrules/placement-policy-enableclusterlogforwarder
#  - ../../base/core/configmaps/lokistack-config
#  - ../../base/core/deployments/lokistack-distributor
#  - ../../base/core/deployments/lokistack-gateway
#  - ../../base/core/deployments/lokistack-querier
#  - ../../base/core/deployments/lokistack-query-frontend
#  - ../../base/core/statefulsets/lokistack-compactor
#  - ../../base/core/statefulsets/lokistack-index-gateway
#  - ../../base/core/statefulsets/lokistack-ingester
