apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nerc-cluster-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes/nerc-ocp-prod/
