apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: observability-metrics
  namespace: grafana
  labels:
    app.kubernetes.io/instance: grafana-obs
spec:
  name: observability-metrics
  datasources:
    - name: observability-metrics
      access: proxy
      editable: false
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsAuth: true
        tlsAuthWithCACert: true
      secureJsonData:
        httpHeaderValue1: "Bearer ${GF_AUTH_TOKEN}"
        tlsCACert: "${GF_TLSCACERT}"
        tlsClientCert: "${GF_TLSCLIENTCERT}"
        tlsClientKey: "${GF_TLSCLIENTKEY}"
      type: prometheus
      url: 'https://observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/metrics/v1/default'
