apiVersion: loki.grafana.com/v1beta1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-operators-redhat
spec:
  managementState: Managed
  storage:
    secret:
      name: thanos-object-storage
      type: s3
  template:
    compactor:
      replicas: 0
      nodeSelector:
        name: none
    distributor:
      replicas: 0
      nodeSelector:
        name: none
    gateway:
      replicas: 1
    indexGateway:
      replicas: 0
      nodeSelector:
        name: none
    ingester:
      replicas: 0
      nodeSelector:
        name: none
    querier:
      replicas: 0
      nodeSelector:
        name: none
    queryFrontend:
      replicas: 0
      nodeSelector:
        name: none
  tenants:
    mode: openshift-logging
  size: 1x.extra-small
  storageClassName: ocs-external-storagecluster-ceph-rbd
