# Source: csi-wekafsplugin/templates/controllerserver-security-context-constraint.yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: csi-wekafsplugin-controller-scc
allowHostIPC: false
allowHostPID: false
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
readOnlyRootFilesystem: false
allowHostPorts: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:csi-wekafsplugin:csi-wekafsplugin-controller
volumes:
  - '*'
