apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: csi-driver-nfs
resources:
  - core/namespaces
  - rbac.authorization.k8s.io/clusterroles
  - rbac.authorization.k8s.io/clusterrolebindings
  - rbac.authorization.k8s.io/rolebindings
  - core/serviceaccounts
  - core/daemonsets
  - core/deployments
  - storage.k8s.io/csidrivers
  - storage.k8s.io/storageclasses
