apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: metallb-operator
spec:
    channel: stable
    installPlanApproval: Manual
    name: metallb-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
