apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
commonLabels:
  app: minio

resources:
- externalsecret-minio-admin-credentials.yaml
- deployment.yaml
- pvc.yaml
- service.yaml
- console-route.yaml
- object-storage-route.yaml
