apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
