apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: acm-metrics-2ti-backing-store
  namespace: openshift-storage
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 2Ti
    storageClass: acm-metrics-2ti-bucket-storage
  type: pv-pool
