apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: acm-metrics-2ti-bucket-class
  namespace: openshift-storage
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - acm-metrics-2ti-backing-store
