apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry
  namespace: opentelemetry
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/ai-telemetry/opentelemetry
