apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry-admin-credentials
  namespace: opentelemetry
spec:
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-obs/ai-telemetry/opentelemetry
