apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client-secret
  namespace: grafana
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: oauth-client-secret
  data:
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: nerc/nerc-ocp-obs/dex/dex-clients
      property: GRAFANA_SECRET
  dataFrom:
  - extract:
      key: nerc/nerc-ocp-obs/dex/grafanas
