apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: logging
resources:
- ../../base/core/namespaces/grafana
- ../../base/operators.coreos.com/operatorgroups/grafana
- ../../base/operators.coreos.com/subscriptions/grafana-operator
