apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-clients
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: nerc-ocp-obs/dex/dex-clients
