apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acct-mgt
resources:
  - ../../base
  - externalsecret.yaml
patches:
  - path: patches/configmap_patch.yaml
  - path: patches/deployment_patch.yaml
