# Source: csi-wekafsplugin/templates/controllerserver-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-wekafsplugin-controller
  namespace: csi-wekafsplugin
  labels:
    app: csi-wekafsplugin-controller
    component: csi-wekafsplugin-controller
    release: csi-wekafsplugin
