apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nerc-api-proxy
commonLabels:
  app: api-proxy
resources:
- namespace.yaml
- deployment.yaml
- rolebinding.yaml
- role.yaml
- route.yaml
- serviceaccount.yaml
- service.yaml

configMapGenerator:
  - name: haproxy-config
    files:
      - haproxy.cfg
